#!/bin/bash
:"${ORDER:?Need to set ORDER. Value between 1-12}"
mkdir -p ./build/build_lina/src
rm ./build/build_lina/src/*.o
rm ./build/lina
CXXFLAGS="-Wall -Werror -ansi -O3 -DNDEBUG -DCONVERGENCE_ORDER=$ORDER -Isrc -xMIC-AVX512 -qopenmp"
mpiicc -c -o build/build_lina/src/GEMM.o $CXXFLAGS  src/GEMM.cpp
mpiicc -c -o build/build_lina/src/GlobalMatrices.o $CXXFLAGS src/GlobalMatrices.cpp
mpiicc -c -o build/build_lina/src/InitialCondition.o $CXXFLAGS src/InitialCondition.cpp
mpiicc -c -o build/build_lina/src/Kernels.o $CXXFLAGS src/Kernels.cpp
mpiicc -c -o build/build_lina/src/Model.o $CXXFLAGS src/Model.cpp
mpiicc -c -o build/build_lina/src/Simulator.o $CXXFLAGS src/Simulator.cpp
mpiicc -c -o build/build_lina/src/WaveFieldWriter.o $CXXFLAGS $HDF5_INC src/WaveFieldWriter.cpp
mpiicc -c -o build/build_lina/src/main.o $CXXFLAGS src/main.cpp
mpiicc -o build/lina build/build_lina/src/main.o build/build_lina/src/Kernels.o build/build_lina/src/GEMM.o build/build_lina/src/Model.o build/build_lina/src/GlobalMatrices.o build/build_lina/src/Simulator.o build/build_lina/src/WaveFieldWriter.o build/build_lina/src/InitialCondition.o $HDF5_LIB $SZIP_LIB -lz -qopenmp

